### ISSUE TITLE
Support USI protocol

### ISSUE THREAD

**Issue by enriqueav** [gunyarakun/python-shogi#11]
In the To Do list there is this item "Support USI protocol.".
What needs to be implemented?
I see the most important part is done: `board.push_usi(string)`

Unfortunately the english version of the USI description is down:
http://www.glaurungchess.com/shogi/usi.html

Do you know by chance if there is a mirror in english? I could not find it.

**Comment by gbtami** [comment]
https://web.archive.org/web/20150326001450/http://www.glaurungchess.com/shogi/usi.html

**Comment by enriqueav** [comment]
@gbtami  thank you!

**Comment by gunyarakun** [comment]
The main purpose of supporting USI protocol is to use Shogidokoro and ShogiGUI which is a Windows GUI application communicates in USI protocol.
http://www.geocities.jp/shogidokoro/index.html (Shogidokoro, The page is written in Japanese)
http://shogigui.siganus.com/ (ShogiGUI, The page is written in Japanese)

**Comment by enriqueav** [comment]
But most of the commands are related to a "thinking engine", right?
I think we need to analyze which parts of USI make sense for a framework like this.

**Comment by gunyarakun** [comment]
Here are the commands supported in Shogidokoro written in Japanese.
http://www.geocities.jp/shogidokoro/usi.html

`python-shogi` is a library for all the programmer who want to write Shogi-related softwares.
I supported [CSA protocol](http://www2.computer-shogi.org/protocol/tcp_ip_server_12_e.html) wrapper in `shogi/CSA.py` for [floodgate](http://wdoor.c.u-tokyo.ac.jp/shogi/floodgate.html).
I suppose someone who want to write "thinking engine" may use USI protocol wrapper to communicate with such kind of Shogi UI softwares.

**Comment by gbtami** [comment]
@enriqueav  https://github.com/johncheetham/gshogi seems to support USI. Maybe it can help to start with.

**Comment by enriqueav** [comment]
@gunyarakun @gbtami thanks, I will take a look at the CSA protocol (I'm not familiar with that) and your implementation, and I will also check what gshogi does...

**Comment by SriMethan** [comment]
@gunyarakun This should be closed since python shogi supports usi protocol

**Comment by gunyarakun** [comment]
@SriMethan Thank you!
