### ISSUE TITLE
ライブラリ登録のお願い

### ISSUE THREAD

**Issue by bleu48** [gunyarakun/python-shogi#14]
予てよりありがたく利用させていただいております。
大変厚かましいお願いですが，コンピュータ将棋選手権使用可能ライブラリへの登録をお願いできませんでしょうか。
http://www2.computer-shogi.org/library/

昨年秋の電王トーナメントでも使用者の多いライブラリのひとつでした。
電王トーナメント主催のドワンゴ社に対しては私からの依頼でよかったのですが，
コンピュータ将棋協会主催のコンピュータ将棋選手権の規定では開発者本人の申請が必要とのことです。
お手数とは思いますが，ご登録頂ければ幸いです。
不適切でしたら削除して下さい。

**Comment by gunyarakun** [comment]
早速申請しようとしたのですが、機能説明を書くのが面倒で。誰か埋めたら申請しておきます！

```
●申請ライブラリ名: python-shogi
●申請者の氏名: 末永匡
●申請者の現住所: xxx
●主要な開発者名: 末永匡(グニャラくん)
●申請ライブラリのURL:
https://pypi.python.org/packages/e6/75/6df7f9ce4478d75d3e4e234740c884c32aadf628ac4e7f40d684ec27b020/python-shogi-1.0.6.tar.gz
●印刷してA4一枚になる程度の機能説明:
(但し、申請ライブラリが別のライブラリをもとにして改変を加えたものの場合、もとのライブラリを明らかにした上で、改変を加えた部分の説明を明記すること。)

FIXME: 面倒だなあ

python-chess
https://github.com/niklasf/python-chess

●作成者指定サイトがある場合、そのURI:
GitHub: https://github.com/gunyarakun/python-shogi
```

**Comment by bleu48** [comment]
遅くなってすみません。
テンプレートまで記入してお願いすべきでした。
機能説明の部分ですが，READMEの要約で以下のようなものでどうでしょうか。
英語でも構わないと思いますが他のライブラリも日本語でしたので簡単にまとめました。
CSAのサイトの説明文でこれより短いものもありますので大丈夫と思いますが，
短いということなら英語版のREADMEでいいと思います。
お手数ですが，よろしくお願いします。
---
これはPythonで書かれたコンピュータ将棋用のモジュールです

python-chess commit 6203406259504cddf6f271e6a7b1e04ba0c96165 に基づいています

* Python 2.7およびPython 3.3以降をサポートしています

* 標準将棋（本将棋）をサポート

* アスキー文字および漢字での局面表示機能

* 合法手生成および合法手検証機能

* 局面への指し手着手および差戻機能

* 詰み判定，千日手判定，当たり判定等の機能

* USI表記の指し手，SFEN表記の局面への対応

* KIF形式棋譜の読み書き対応

* CSAプロトコル通信対応

* 思考部は搭載されていません

**Comment by gunyarakun** [comment]
追加されました！
http://www2.computer-shogi.org/library/
バージョンアップごとに申請必要なのかな、これ……!?
