### ISSUE TITLE
All moves starting at 0 are illegal

### ISSUE THREAD

**Issue by pec72** [gunyarakun/python-shogi#15]
Hi,

The actual test for a legal moves is incorrect when from_square is 0 (9a)
The test should be :

    if move.from_square is not None

https://github.com/gunyarakun/python-shogi/blob/6422e949ced4952e1831d428387408bf4fd800ba/shogi/__init__.py#L865

**Comment by gunyarakun** [comment]
Hi @pec72,
I appreciate you reported the problem!
I fixed the issue in the commit 3264b7fb8697551668bcf8240d2eb4654be9b07d.
