### ISSUE TITLE
消費時間情報のついているKIF形式のパース

### ISSUE THREAD

**Issue by kmo2g** [gunyarakun/python-shogi#16]
手数----指手---------消費時間--
   1 ７六歩(77)   ( 1:00/00:01:00)
このように将棋時間がついているとKIF形式ファイルのパースがうまくいかないようです。
KIF.pyにあるMOVE_RE変数の正規表現から\Zを削除すれば取りあえずはパースできるようです。

**Comment by gunyarakun** [comment]
おお、なるほど。
https://tmsanrinsha.net/post/2018/04/kifu-for-js/
読みながら実装なおしてみます。

**Comment by gunyarakun** [comment]
5691e3c323a13885ab55ebac6381c9d4c68b160a
で修正しました

**Comment by kmo2g** [comment]
ありがとうございます
