### ISSUE TITLE
legal-check bug

### ISSUE THREAD

**Issue by peanatsu** [gunyarakun/python-shogi#17]
hello, I have a problem with move-legality check. Attached a minimal example to show the problem. The move is legal, but it is not recognized as such with `move in board.legal_moves`. When generating the full list of legal moves, it is recognized.
I am using python version 2.7.13 on debian with python-shogi version 1.0.7

```
import shogi

b = shogi.Board()
b.set_sfen('ln1g3+Rl/1ks4s1/pp1gppbpp/2p3N2/9/5P1P1/PPPP1S1bP/2K1R1G2/LNSG3NL w 4p 42')
m = shogi.Move.from_usi('2g5d+')

print(m in b.legal_moves)                   # False
print(b.legal_moves.__contains__(m))        # False
print(m in list(b.legal_moves))             # True
print(list(b.legal_moves).__contains__(m))  # True
```

**Comment by gunyarakun** [comment]
@peanatsu Thank you for pointing out the issue.
I fixed the problem in the commit 5264ea466b4c58463f56db0d77cb9157cb7c535c.
