### ISSUE TITLE
KIF parsing of non-promotion 不成

### ISSUE THREAD

**Issue by ianfab** [gunyarakun/python-shogi#54]
I encountered a [kifu](https://shogidb2.com/games/d11ac17fa3472096419d569d444625b26f079e51#kng1%2BN2nl%2Fls7%2F1%2BS1pB3p%2F2p4p1%2FP3B4%2FLGs5P%2F1Ps2P3%2F1K4P1r%2F1N1P4%2Br%20b%201L7P2g1p%20101) where a silver move refraining from promotion seems to explicitly contain this information using the suffix `不成`.

```
100 ７七銀不成(68) (00:00/00:00:00)
```

As a quick workaround I simply [normalize this suffix away](https://github.com/ianfab/python-shogi/commit/b1ff8c5ff7ce6ee235ee54294d60fdc84d791b3c). If you consider this a sufficient fix I can also raise a PR, otherwise I guess you might want to adjust the regex for parsing.

**Comment by gunyarakun** [comment]
At first, sorry for my late response, @ianfab san.

In the formal document of KIF file, they say `不成の場合は、「不成」を表記しない。` (If not promoted, don't put `不成`).
http://kakinoki.o.oo7.jp/kif_format.html
So the KIF file is invalid originally.

To handle such kind of invalid KIF files, just replacing `不成` to `` as you did is a good solution.

**Comment by ianfab** [comment]
Thanks for your feedback. Just created a corresponding PR.
