### ISSUE TITLE
反則か勝ち

### ISSUE THREAD

**Issue by TadaoYamaoka** [gunyarakun/python-shogi#58]
https://github.com/gunyarakun/python-shogi/blob/f27c6ad5656ce9c260802992d6def1bb1bfc4fa8/shogi/KIF.py#L179

「反則か勝ち」は、「反則勝ち」のタイプミスではないでしょうか。

**Comment by gunyarakun** [comment]
@TadaoYamaoka ご指摘ありがとうございます！修正いたします。
