### ISSUE TITLE
指し手生成にバグ？

### ISSUE THREAD

**Issue by bleu48** [gunyarakun/python-shogi#6]
偶然見つけたのですが，以下の後手番の局面のときに８筋に歩を打つ手を不正とみなすようです。

# 最小バグ生成コード
board = shogi.Board('lr7/3skgg1+B/2n2s1pp/p1p1ppP2/3p1np2/1PPPP4/PS1G1P2P/2GS3R1/LNK4NL w L2pb 58')

moves = []
for move in board.legal_moves:
    moves.append(move.usi())

print(board.kif_str())
print(moves)

**Comment by gunyarakun** [comment]
指摘ありがとうございます！

二歩で相手側の歩まで考慮していたというバグでした…
ccc61a95593f15904d4363ba847887417270f2c9
で修正の上、v1.0.4をリリースしました。

**Comment by bleu48** [comment]
素早い対応ありがとうございます。確認しました。
