### ISSUE TITLE
kif.exporter.kif() and kif parse.parsefile() win result is not same

### ISSUE THREAD

**Issue by sugizo** [gunyarakun/python-shogi#61]
tested on google colab, using the steps mention on [pypi.](https://pypi.org/project/python-shogi/)

as you can see in this image below, 
the exporter written, win : b

but 

when save it into file and parse again, 
the win result is different, win : w

![image](https://user-images.githubusercontent.com/2418295/229426873-731a562b-efad-4ae2-98e6-10e967262f49.png)

best regards

**Comment by gunyarakun** [comment]
@sugizo 
Thank you for your report.
An example code in `README.rst` was wrong, the `win` must be `w` in that case.
I added a test case to check the inconsistency in the pull request #63.
The sample code you wrote will raise an exception in the new version.
