### ISSUE TITLE
合法手の判定について

### ISSUE THREAD

**Issue by nakahiray200** [gunyarakun/python-shogi#7]
こんにちは。
合法手の判定の仕方でちょっとわからないことがあったので教えてください。
sfen文字列で局面を読み込んで、指し手を入力してみたところ、どうしても合法手の判定になりません。
sfenは　lnsg1g1nl/3k3r1/pppp1s1pp/b3p1p2/2PP1p2B/P3P3P/1P3PPP1/1S3K1R1/LN1G1GSNL w - 1　で9dの地点の角が6gの地点に移動しようとすると、falseが返ってきます。王手ではないようですし、何が原因なのかわかりません。
よろしくお願いします。

>>> board = shogi.Board("lnsg1g1nl/3k3r1/pppp1s1pp/b3p1p2/2PP1p2B/P3P3P/1P3PPP1/1S3K1R1/LN1G1GSNL w - 1")
>>> s = shogi.Move.from_usi("9d6g") in board.legal_moves;
>>> print(s)
False

**Comment by gunyarakun** [comment]
おお、おかしそうですね(9d8eと9d7fだけしかない)。修正します！

**Comment by gunyarakun** [comment]
修正しました。#8も修正したあとリリースします。
