### ISSUE TITLE
Null move の bool判定がTrueになる

### ISSUE THREAD

**Issue by y-ochiai** [gunyarakun/python-shogi#9]
Null moveを
`return cls(0, 0, NONE)`
で作っているので、
from_square とto_square が両方とも0になると思います。

そうすると、
```
    def __bool__(self):
        return self.to_square is not None
```
が、Falseにならないと思うのですが、いかがでしょうか？

この影響で、
`board.push(shogi.Move.null())`
としたときに、手番の変更だけでなく、9aの駒を9aの駒で取るような動作になってしまいます。

**Comment by enriqueav** [comment]
How to observe:

Initialize a board with Lances in hand:

```python
>>> import shogi
>>> board = shogi.Board('lnsgkgsn1/1r5b1/ppppppppp/9/9/9/PPPPPPPPP/1B5R1/LNSGKGSN1 b Ll 1')
>>> print(board)
 l  n  s  g  k  g  s  n  .
 .  r  .  .  .  .  .  b  .
 p  p  p  p  p  p  p  p  p
 .  .  .  .  .  .  .  .  .
 .  .  .  .  .  .  .  .  .
 .  .  .  .  .  .  .  .  .
 P  P  P  P  P  P  P  P  P
 .  B  .  .  .  .  .  R  .
 L  N  S  G  K  G  S  N  .

 L*1 l*1
```
Then, pushing a null move will a lance to be pushed to captured_piece_stack:

```python
>>> board.push(shogi.Move.null())
>>> board.captured_piece_stack
deque([2])
```
This is especially harmful if a pop() is executed for this move, because it will erase the lance in hand

```python
>>> board.pop()
Move.from_usi('9a9a')
>>> print(board)
 l  n  s  g  k  g  s  n  .
 .  r  .  .  .  .  .  b  .
 p  p  p  p  p  p  p  p  p
 .  .  .  .  .  .  .  .  .
 .  .  .  .  .  .  .  .  .
 .  .  .  .  .  .  .  .  .
 P  P  P  P  P  P  P  P  P
 .  B  .  .  .  .  .  R  .
 L  N  S  G  K  G  S  N  .

 l*1
>>> 
```

**Comment by enriqueav** [comment]
I would like to contribute with this repo.
I have created a pull request with the fix and unit tests.

**Comment by gunyarakun** [comment]
@y-ochiai 指摘ありがとうございます。オリジナルのpython-chessも同じ問題抱えていそう、と思って現状の版を見たら、from/toの両方をチェックしているようになっていて、実質問題ないようになっていました。v1.0.6もリリースしました。

@enriqueav Thank you for your contribution. That fixes the problem. I've release v1.0.6 including your commits.

**Comment by enriqueav** [comment]
@gunyarakun Thank you! I'm just starting working with Python but I have experience developing a Shogi engine and AI players in Java. I'm open to contribute in this repo, if you have a "to do", or if more bugs are encountered...

**Comment by gunyarakun** [comment]
@enriqueav ToDo list is here: https://github.com/gunyarakun/python-shogi#todo
I feed happy to hear you are open to contribute in this project!
